name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  setting:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: install node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: install-app
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
